### ISSUE TITLE
Merge `BasicProverEnvironment` and `ProverEnvironment`?

### ISSUE THREAD

**Issue by cheshire** [sosy-lab/java-smt#109]
@PhilippWendler looking at the interface further after #108,
it seems that the interface can be considerably simplified by merging `BasicProverEnvironment` and `ProverEnvironment`.
All of the functions declared in `ProverEnvironment` could be used in the interpolating context as well,
and the change would simplify the documentation as well, removing the redundancy in JavaDoc comments.

**Comment by PhilippWendler** [comment]
- [ ] Would this mean merging the two interfaces completely such that effectively we have only one left, or is this just about moving all features that are currently present in `ProverEnvironment` to `BasicProverEnvironment` because they would work there, too?
- [ ] Is merging two interfaces of which one most people do not need to care about really a "considerable" simplification, i.e., does it add significant cost to using or understanding the API?
- [ ] Does it make sense to have these features available in `InterpolatingProverEnvironment`? Is it probable that people actually make use of both interpolation and those other features at the same time? Could combining these features lead to people just call `newProverEnvironmentWithInterpolation()` all the time without thinking about it, and then get lower performance due to the overhead of proofs than they could get otherwise?
- [ ] Are all these features from `ProverEnvironment` compatible with `OptimizationProverEnvironment` as well?
- [ ] Does the same probably hold for all future features that we would to `ProverEnvironment`, and for all future sub-interfaces?
- [ ] Would you remove one of the two interfaces completely, or keep one as `@Deprecated` for easier transition?
- [ ] Why stop at merging `BasicProverEnvironment` and `ProverEnvironment`? Why don't merge `InterpolationProverEnvironment` and `OptimizationProverEnvironment` with the others as well and only use feature flags? Where do we draw the line and with what reasons?

**Comment by cheshire** [comment]
> Would this mean merging the two interfaces completely such that effectively we have only one left

yes.

> does it add significant cost to using or understanding the API

no, just means environments for interpolation/optimization would also expose methods for unsat core and allsat.

> Does it make sense to have these features available in InterpolatingProverEnvironment

why not? We do support assumptions there.

> Could combining these features lead to people just call newProverEnvironmentWithInterpolation() all the time without thinking about it

no, why? with respect to `isUnsat` calls, nothing will be changed.

> Are all these features from ProverEnvironment compatible with OptimizationProverEnvironment as well?

no, doesn't seem to support solving with assumptions.
The limitation is specific to Z3 solver though, and I would be happy to throw `UnsupportedOperationException`.

> Does the same probably hold for all future features that we would to ProverEnvironment, and for all future sub-interfaces?

I would say yes.

> Would you remove one of the two interfaces completely, or keep one as @Deprecated for easier transition?

Remove, it seems user code is unlikely to use `BasicProverEnvironment`.

> Why don't merge InterpolationProverEnvironment and OptimizationProverEnvironment with the others as well and only use feature flags?

We could. Yet then the interface would have a lot of methods, and it would be quite confusing which feature enables which methods.
Thus I think we should stop at the proposed merge.

**Comment by kfriedberger** [comment]
The methods for computing allsat and unsat core are moved upwards into the `BasicProverEnvironment`.
The interfaces themselves are kept, because `addConstraint` returns a handle for `InterpolatingProverEnvironment` and `Void` for other subclasses.
