### ISSUE TITLE
Model#evaluate after closing the prover environment creates a Segmentation Fault

### ISSUE THREAD

**Issue by leostrakosch** [sosy-lab/java-smt#126]
When you first use `ProverEnvironment#getModel()` to get a Model,
then close the ProverEnvironment and then run `Model#evaluate`, a segmentation fault occurs.

I'm using MathSAT5 and run `Model#evaluate` on a `BooleanFormula`.
Is it possible to throw some exception, instead?

**Comment by PhilippWendler** [comment]
Is this fixed?

**Comment by kfriedberger** [comment]
It is fixed as far as possible.
I do not know whether it is a bug or expected behaviour in MathSat5,
that a model becomes unusable after closing the prover.
The documentation for `msat_get_model_value` says `no assert/push/pop/allsat commands have been issued in the meantime`, which can be interpreted as `do not close the prover`. For other methods applied on a model such info is missing.
