### ISSUE TITLE
Use Java binding directly from MathSAT5

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/java-smt#160]
MathSAT 5.3 brings its own Java bindings and build-scripts.
We should evaluate their usage and maybe switch, instead of building and using our own bindings.

The same applies to OptiMathSAT5. See also issue #132.

**Comment by kfriedberger** [comment]
@PhilippWendler Any thoughts about this?

**Comment by PhilippWendler** [comment]
The Java API bundled with MathSAT 5.5.4 has the following disadvantages compared to the code in JavaSMT:
- It is in the package `mathsat`. This might create problems for example if we make use of the module system of Java 9.
- The API class and everything is public, but we want to hide it behind JavaSMT's API.
- The API does not make use of exceptions, but requires checking the error code of each and every function call. In contrast, our own code converts error codes into exceptions using a set of macros, which ensure that this is done for every function without possibility to forget it.
- The API does not check for illegal arguments, but just forwards them to MathSAT. By doing our own argument checks in the same set of macros, we get better understandable errors if a caller does something wrong.
- The C code calls methods like `GetLongArrayElements` or `GetStringUTFChars` of the JNI API without checking for the return value. This can lead to segfaults because of null-pointer dereferences.

**Comment by kfriedberger** [comment]
Ok, I see.
We also use Z3 with its official Java-bindings and there this does not seem to be a problem.
How good/bad are our chances to get Alberto to fix the basic things?
Otherwise we also can continue to build MathSAT5 on our own.

**Comment by PhilippWendler** [comment]
> How good/bad are our chances to get Alberto to fix the basic things?

I do not know.
