### ISSUE TITLE
Unit Test for Solver Stacks

### ISSUE THREAD

**Issue by baierd** [sosy-lab/java-smt#187]
Implement and test the different capabilities of the solvers assertionstacks.
(Princess seems to throw an exception if too many formulas are pushed at once for example)

**Comment by kfriedberger** [comment]
There are two problems here:

### 1
First of all Princess does not support large stacks with simple formulae (or maybe just large formulae).
The test `largerStackUsageTest` fails when checking satisfiability.
The corresponding formulae are:
- `x0==x1 && y0==y1 && x0==y0`
- `x1==x2 && y1==y2 && x1==y1`
- `x2==x3 && y2==y3 && x2==y2`
- ... up to index 1000.

Princess seems to fail even with index 200 with a memory problem.

### 2
Princess seems to have a memory leak or some internal caching that is kept longer than the corresponding solver context (e.g., even after it is closed). It seems as if Princess does not yet fully close the prover stacks (class name: SimpleAPI) and keeps some data longer than expected. Maybe this only happens after the failing solver query with the memory problem as noted above.

I tried to close all components of princess in 32069c7899e2bb00d04d1c654c3f322107c8a124, but did not suceed.
This results in a failing (simple) JUnit test suite (if all tests are executed), until the largest test is disabled in e07cb938283a9ebc063b7f257cbe4c7ebaa49d98. The largest test itself does fail, and additionally does not clean up its data (or something similar), so that, when running the whole test suite and catching the mentioend out-of-memory-error, a following test (`simpleStackTestBool`, test 13 after the memory problem) fails with an out-of-memory. `simpleStackTestBool` does not use much memory and is not expected to fail.

We might need to ask @pruemmer for help here.

**Comment by baierd** [comment]
Interesting.

Did you try to wait for a certain amount of time for garbage cleaning etc. or do you think its a more general issue in Princess?

Did your test provide some information regarding the limits of the other solvers?

**Comment by kfriedberger** [comment]
No other solver had problems with this specific test.
An upper limit of 1000 is sufficient for most use cases anyway, so this should be fine.
Only Princess seems to have problems, but I did not yet debug whether this is a stack-related problem or just undefined behaviour after crashing the solvers with a large SMT query.

Could you check whether Princess can solve the Junit test without using PUSH, i.e., just add constraints and solve them?

**Comment by baierd** [comment]
I tested a few variations:

1. Enableing the `largerStackUsageTest` for Princess and running all solvers (in IDE and $ ant unit-tests) only the newly enabled test fails (w and w/o interpolation) (No the `simpleStackTestBool` did not fail for me here)

2. Exclusively running Princess in the test-suite confirms your problem and fails `simpleStackTestBool` with a memory problem (w and w/o interpolation)

3. Removing `PUSH()` results in Princess calculating for a while (120s+ for me) and then failing with the same memory problem w/o interpolation and failing in around 2s with interpolation. Seems like the mem problem persists but its either worse with  `PUSH()` or the solver notices faster. However in both cases no other test fails!

(w/o interpolation from here onwards)
4. Reducing `PUSH()` to 100 uses fails the test in ~7s and does not fail any other tests for me in any case.

5. Reducing `PUSH()` to 200 (or more) uses fails `simpleStackTestBool` however.

Seems to be stack related.
Maybe its just a lot of objects with references and the garbage collector works a little random at times anyway?
Do you need further testing?

**Comment by kfriedberger** [comment]
As Princess is currently not the most used solver, I would ignore the problem for now.
This issue reports enough data to take a look at it when needed.

One more thing we cna try is dumping the problem as SMT-LIB2 (or just generate it) and query Princess directly, without any parts of JavaSMT.
If this also fails, we can send the data to @pruemmer, so that he can debug the problem.
