### ISSUE TITLE
MathSAT5 crash on model iteration (again)

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/java-smt#208]
The seg-fault from the crashing test case in e9449af needs to be debugged.
A simple C program causing the same bug could help us or Alberto fixing it.

**Comment by baierd** [comment]
I suspected a overflow problem first, hence my comment on the commit. 
But if you lower the value used for `a` it doesn't change, so it is at the very least not caused by us.

If i recreate the exact steps in C it does NOT crash! 
Model and value are ok and have the right values.

**Comment by kfriedberger** [comment]
That might also be a bug in our JNI bindings.

**Comment by baierd** [comment]
Update: 
In version 5.6.3 it crashes because `msat_model_iterator_has_next(iter)` returns `true` when it shouldn't (First invokation is fine, then it keeps returning true the second time its called but there is no second element in the model).

In version 5.6.4pre1 it crashes when creating the iter with `msat_model_create_iterator()` however!

I've checked the current official release as well as the current nightly build with smtlib2 parsing, no problem here.

**Comment by baierd** [comment]
For reasons currently unknown to me our wrapper needs the model and not the environment to create an iterator for the model.

I fixed your tests. But `modelIteratorCrash` runs for a long time without crash on my machine.

**Comment by kfriedberger** [comment]
Of course :exploding_head: I should have read the API documentation.
In C everything is just a `long`.

**Comment by kfriedberger** [comment]
@baierd 
We talked today about a function-parameter-mismatch in the MathSAT5-API, for creates a model iterator.
However, there was a misunderstanding, because there are actually two different methods with similar names:
- [msat_model_iterator msat_create_model_iterator (msat_env e)](https://mathsat.fbk.eu/apireference.html#a0b59387b978f92e04649cce69cce625f)
- [msat_model_iterator msat_model_create_iterator (msat_model m)](https://mathsat.fbk.eu/apireference.html#a24612e582a4697caf4dcc9d3bfc1a28a)

One takes a model, the other one takes a environment.

**Comment by baierd** [comment]
That solves that mystery.
Deceptive API naming here.
