### ISSUE TITLE
Improve Quantification Support for some Solvers

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/java-smt#218]
Several SMT solvers provide the possibility to create quantified SMT queries, either via their API or at least via an SMTLIB-based String.
We should support this, and provide proper handling and visitor implementations.

Currently, there are two types of SMT solvers, depending on the kind of symbols that is used in the quantified formula:
- either the quantified variable is a **normal symbol**, created via `*FormulaManager.createVariable`.  
  In this case, the handling is quite simple and we do not further need to manipulate the formula.
- or the quantified variable is a **bound variable** and needs to be created with some special API call.  
  In this case, we might want to create the variable just like a normal variable and, when building the quantified query, we need to substitute the free variable with a newly created bound one in the formula body. The same substitution needs to be applied backwards when the body is analyzed, e.g., by a FormulaVisitor. Overall, for a user's application, we only want to provide `one` method to create a symbol and not distinguish by later usage as free or bound variable.

Additionally, we need to define whether a bound symbol should be returned when collecting symbols and UFs from a formula.
This step might already be inconsistent now between e.g., MathSAT and Z3.

**Comment by baierd** [comment]
The rework of the CVC4 quantifiers is done. Quantified formulas work properly and quantifier elimination is now useable. Some tests were added, especially for nested quantified formulas and model handling for bound vars (CVC4 does not return any values for bound var, even in UFs).


All bound variables are introduced only internally when a quantified formula is created and they are re-substituted to their original free counterparts once you visit them. If you visit a quantified formula, the free var will be returned in the bound var category of the visitor. So the user has no access to any of the bound vars. If a new formula is built, or an old one is manipulated with the visitor, a new bound var is introduced again, repeating the process. I've tested this for the regular and the recursive visitor. (Which does not mean that more tests wouldn't be good)

The changes can be seen in the branch [cvc4_quantifier](https://github.com/sosy-lab/java-smt/tree/cvc4_quantifier).
(The tests fail because of issue #239 which has nothing to do with the quantifiers.)

**Comment by kfriedberger** [comment]
Current status:
- no exposure of bound variables in any way towards the user, but we only provide free variables.
- JavaSMT supports quantification as far as the solvers support it. This includes the solvers Boolector, CVC4, Princess, and Z3.

This is a valid result for now. Closing the issue.
