### ISSUE TITLE
BooleanFormulaVisitor doesn't behave as expected / BitVectorFormulaVisitor missing

### ISSUE THREAD

**Issue by MartinSpiessl** [sosy-lab/java-smt#222]
I implemented a `BooleanFormulaVisitor` and want to visit the following formula:
```
(`=_<BitVec, 32, >` x 42_32)
```
Since there is no `BitvectorFormulaVisitor`, I would expect that the bitwise equality is also considered here. However, this is currently not the case, it is treated as atom,
as can be seen in `org.sosy_lab.java_smt.basicimpl.AbstractBooleanFormulaManager$DelegatingFormulaVisitor`:
https://github.com/sosy-lab/java-smt/blob/44876b206ec46d27d650de593470959cd4a3aed0/src/org/sosy_lab/java_smt/basicimpl/AbstractBooleanFormulaManager.java#L399-L401

Now I can understand why bitvector equality isn't considered actual boolean equality, but then I would expect that there is similar a way to visit bitvector formulas. Or does that already exist and I just didn't find it?

As I understand the current API, I am supposed to use `FormulaVisitor` and switch on the function type inside `visitFunction` myself, right? I can do that no problem, just wanted to make sure I didn't miss something.

**Comment by kfriedberger** [comment]
That looks like a bug in our implementation, because we already have `FunctionDeclarationKind.BV_EQ` (which seems to be unused currently).
Can you give details about the used solver?
I will investigate it and possibly provide an updated version soon.

**Comment by kfriedberger** [comment]
Ok, perhaps I did not read properly before assigning the bug label.
Taking a second look, the behaviour of the `BooleanFormulavisitor` seems to be correct here, because a BV formula is not a boolean one. Splitting it into bits might be possible, but maybe not wanted by the user, as this would mix up theories.

For `DefaultBooleanFormulaVisitor#visitDefault` we could introduce an overloaded default implementation that could be overridden and forwards to the existing method. This might not even result in an incompatible interface. I will think about it.

**Comment by kfriedberger** [comment]
And a third look:
Providing the formula itself as parameter for `visitDefault` might really break the interface, because for several types of formulas, there is no existing such argument in the calling method, e.g., in `visitAnd`/`visitOr` there is only the list of components and `visitConstant` provides none. Thus, we would either need to rebuild the information based on the context, which results in some overhead, or we add the required parameters to all methods, which is an incompatible change to the public interface.

**Comment by MartinSpiessl** [comment]
Thanks, everything clear here as far as that goes now. If you want to enhance the default visitor feel free to do so, otherwise the issue can also be closed immediately.
