### ISSUE TITLE
Question: Get Arguments from UF-Function

### ISSUE THREAD

**Issue by jfh1911** [sosy-lab/java-smt#234]
Hey,
i hope that this is the right place to ask this question:

For the minimal example below, I want to get the variables `a` and `b` as `Formula` Objects.
Is there a way to get these arguments given to an called UF?
Within the formulaVisitor, I only get the type of the arguments but not the arguments itself.

(My usecase: I parse a SMT formula with the FormulaManager and want to visit the parts, especially want to get the arguments within the functions present)

Minimal example:
```java
SolverContext context = SolverContextFactory.createSolverContext(Configuration.defaultConfiguration(),
		LogManager.createTestLogManager(), ShutdownNotifier.createDummy(), Solvers.Z3);
IntegerFormulaManager imgr = context.getFormulaManager().getIntegerFormulaManager();
FormulaManager fmgr = context.getFormulaManager();
BooleanFormulaManager bmgr = fmgr.getBooleanFormulaManager();

//Create the variables and uf
IntegerFormula a = imgr.makeVariable("a");
IntegerFormula b = imgr.makeVariable("b");
BooleanFormula uf = fmgr.getUFManager().declareAndCallUF("testFunc", FormulaType.BooleanType, a, b);
System.out.println(uf);

bmgr.transformRecursively(uf, new BooleanFormulaTransformationVisitor(fmgr) {

	@Override
	public BooleanFormula visitAtom(BooleanFormula pAtom, FunctionDeclaration<BooleanFormula> decl) {
		System.out.println(decl);
		return super.visitAtom(pAtom, decl);
	}
});
```

**Comment by kfriedberger** [comment]
Yes, this is the right place to ask, because Github allows convenient cross-referencing.

The answer to your question is: A visitor is the right way to go, but your code uses the wrong visitor.
A `BooleanTransformationVisitor` should only be used for special cases, where the return value needs to be a boolean formula. It aims at keeping the internal structure of the given formula. The general `FormulaVisitor` is the better choice here, and it allow to access the arguments of a function application in the corresponding method.
```
    FormulaVisitor<Collection<Formula>> argCollectingVisitor =
        new DefaultFormulaVisitor<>() {

          final Collection<Formula> usedArgs = new LinkedHashSet<>();

          @Override
          public Collection<Formula> visitFunction(
              Formula pF, List<Formula> args, FunctionDeclaration<?> pFunctionDeclaration) {
            usedArgs.addAll(args);
            return usedArgs;
          }

          @Override
          protected Collection<Formula> visitDefault(Formula pF) {
            return usedArgs;
          }
        };

    Collection<Formula> usedArgs = mgr.visit(uf, argCollectingVisitor);
```
I added a JUnit test in 6f4c021666190af96f2c5d541eb899cb363d961f as an example for your case:
