### ISSUE TITLE
Solver timeout

### ISSUE THREAD

**Issue by hernanponcedeleon** [sosy-lab/java-smt#241]
Is there any way to configure the timeout for the SMT solver from the configuration?
I could not find any such option [here](https://sosy-lab.github.io/java-smt/ConfigurationOptions.txt).

**Comment by PhilippWendler** [comment]
Adding the possibility to configure a time limit is highly complex and opens many questions: Should this be per query? Accumulated per prover? Per solver context? Global? Are nested time limits needed? Limits for CPU time or for wall time? Do only solving operations count or also other potentially costly operations? Or even all solver operations?

I guess there would either need to be lots of configuration options, or it would be too inflexible in practice. Thus it does not seem to be a good fit for a low-level library like JavaSMT and instead should be implemented at a higher level, typically in the application that knows what kind of time limit it wants.

And JavaSMT already cooperates well with applications that implement such time limits: After it has determined that the time limit has elapsed, the application simply needs to call `ShutdownManager.requestShutdown()` on the `ShutdownManager` instance that belongs to the `ShutdownNotifier` that was passed to JavaSMT. JavaSMT and all solvers that support this will then stop at the earliest possibility (though no immediate stop can be guaranteed).

Note that the solver context won't be able to be reused after a shutdown has been requested. This is in general a limitation of the solvers, because it is not clear that the context is left in a clean state.

**Comment by hernanponcedeleon** [comment]
Thanks for the pointer @PhilippWendler. I manage to implement this at the application level using the `ShutdownManager `.
