### ISSUE TITLE
Most significant bit

### ISSUE THREAD

**Issue by hernanponcedeleon** [sosy-lab/java-smt#266]
Is this the correct way of computing the most significant bit of a bit-vector?
```
BitvectorFormula bv = bvmgr.extract(bv, bvmgr.getLength(bv), bvmgr.getLength(bv), true);
```
I'm particularly not sure about the last parameter.

**Comment by kfriedberger** [comment]
Hi Zeta,

Your approach should nearly work.
Without looking into the code, I would guess that the access to the most
significant bit works with an index “length-1” instead of “length”, similar
to array-access in most programming languages.

The operation “extract” does not use the signess-flag (in most or even all
solvers). We already think about removing this parameter in some upcoming
version.

Best,
Karlheinz


Am Mittwoch, 13. April 2022 schrieb Zeta ***@***.***>:

**Comment by hernanponcedeleon** [comment]
Thanks for the clarification @kfriedberger

**Comment by kfriedberger** [comment]
Postscript: The signed-flag in the operation EXTRACT is removed with d9593c9e99791240bc161f2798e9d055d3471d28.
