### ISSUE TITLE
Unary minus treatment in visitors

### ISSUE THREAD

**Issue by cheshire** [sosy-lab/java-smt#28]
Do we want a special treatment for unary minus in visitors?
That is, converting to the constant, and applying the negation.

I would say "no", as for some constants I'm not sure how it could be applicable (e.g. bitvectors).
But the behavior should be consistent across all solvers --- at the moment SMTInterpol does perform this trick.

**Comment by PhilippWendler** [comment]
We need to handle unary minus for generating the values of models, this is important.
For visitors I think both ways are ok, though it is probably preferable if the result is similar across all solvers, and if we handle unary minus as part of the number, we help clients because they do not need to handle it themselves (and can't forget it, which would happen quite often if one solver has negated numbers and the others return a unary minus operator applied to a positive number).

**Comment by cheshire** [comment]
Turns out that code for SmtInterpol was completely unnecessary in the model case, and used only for visitors. For models SMTInterpol promises to always return Rational or BigInteger.
