### ISSUE TITLE
Latest JavaSMT depends on a version of common not in maven repository

### ISSUE THREAD

**Issue by hernanponcedeleon** [sosy-lab/java-smt#280]
[This](https://repo1.maven.org/maven2/org/sosy-lab/java-smt/3.13.3/java-smt-3.13.3.pom) version of JavaSMT depends on `org.sosy-lab:common:jar:0.3000-529-g6152d88`. However, the latest available version in the maven repository is [this](https://repo.maven.apache.org/maven2/org/sosy-lab/common/0.3000-502-gb581f5d/) one (which is an older one).

**Comment by kfriedberger** [comment]
Thanks for reporting. This issue will be fixed soon.

**Comment by kfriedberger** [comment]
Fixed, the correct version was [pushed to Maven](https://repo.maven.apache.org/maven2/org/sosy-lab/common/0.3000-529-g6152d88/).

**Comment by hernanponcedeleon** [comment]
I wanted to try the new release, but I get his problem
```
The following artifacts could not be resolved: org.sosy-lab:common:jar:0.3000-568-gb81232a9 (absent): Could not find artifact org.sosy-lab:common:jar:0.3000-568-gb81232a9 in central (https://repo.maven.apache.org/maven2) 
```
Version 4.0.0 has this dependency
```
<dependency>
<groupId>org.sosy-lab</groupId>
<artifactId>common</artifactId>
<version>0.3000-568-gb81232a9</version>
<scope>compile</scope>
</dependency>
```
but the artifact in the repository is called
```
org/sosy-lab/common/common-0.3000-568-gb81232a9
``` 
which has an extra (?) `common-` prefix.

**Comment by PhilippWendler** [comment]
I guess it is time to implement #79.

**Comment by kfriedberger** [comment]
I released sosy-common-lib in a correct version. Maven will synchronize within a few hours. Issue fixed. :-)

We sould actually implement an automated way of releasing software to Ivy and Maven instead of requiring a user to perform some manual magic.
For example, we could use a separate release branch, where some Github/Gitlab build pipeline is available to deploy the artifact to all target systems.
The branch would need to be protected to only allow some administrative usage.

**Comment by hernanponcedeleon** [comment]
I confirm it works on my side. Thanks @kfriedberger
