### ISSUE TITLE
Rework Model API

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#30]
The class `Model` has a weird API:

- It implements `Map` itself, but also provides redundant access to the underlying `Map` with `getData`.
- `appendModel` should not be `public`
- `TermType` and `FormulaType` are quite inconsistent, which makes the API weird and incomplete, for example there is no way to get for example size of bitvectors from the model.
- Maybe a model should also have a reference to the `Formula` representation of each item?
- Maybe the model-related classes should be in a separate package? They feel out-of-place where they are.

As far as I know there is also no way to get array values from the model currently, this needs to be added.

The documentation to `Model` is practically nonexistent. It needs to explain for example which kind of value objects one has to expect in which case, whether the model is full or partial etc.

**Comment by cheshire** [comment]
Ideally `TermType` and `FormulaType` should be merged, but the latter requires knowing the type exactly (how many bits bitvector has), which is not always convenient for getting values out of the model.

For getting values out, wouldn't `evaluate` method be considerably more convenient? Then one could create terms the usual way through `FormulaManager`. Though I do remember there were problems with some solvers not being able to store the model independently of the context, I might need to double-check.

If `evaluate` would work for all solvers, we could remove the dictionary storage entirely, and just use `evaluate` together with iteration. Iteration than could return the `FormulaType`, so we could drop the `TermType` class.

**Comment by cheshire** [comment]
@PhilippWendler 
What about the following code:

```java
public interface Model extends Iterable<Entry<Formula, Object>> {
   Object evaluate(Formula f);
}
```

This is minimalistic, doesn't require any further classes and I believe is sufficient for any operations one might want to do.

**Comment by cheshire** [comment]
Moreover, it would not need extending for extra datatypes (arrays, strings, etc)

**Comment by cheshire** [comment]
Actually `evaluate` should be `@Nullable` to allow for don't-matters.

**Comment by cheshire** [comment]
Additional point: currently we skip array terms when iterating over models.
I think it would be more correct to simply return their string representation.
We can also do that for terms we don't know how to handle (e.g. string, datatypes, etc)

**Comment by stephanlukasczyk** [comment]
@cheshire I put the skip in there when implementing the array support, because I didn't see a method to get the values out of the arrays. I was discussing this with @PhilippWendler, but we didn't decide what to do with the array terms, yet.
In my opinion, a string representation would be fine, if there is no way to get the array values directly.

**Comment by cheshire** [comment]
@stephanlukasczyk Agreed, also with new `eval` API iteration could be used much less.

**Comment by cheshire** [comment]
New API pushed.
I've discovered that returning `Optional` every time on `evaluate` may be quite annoying, maybe we should provide two versions, partial and non-partial models? Z3 supports both, but some solvers (namely Princess) only support partial models.

**Comment by cheshire** [comment]
I've changed `@Nullable` to `Optional`, but now I think we should change it back to `@Nullable`, because:

 - `Optional<Object>` is an annoying interface, since `Optional` is also an object and there is no compile time error if one forgets to call `.get()`
 - Partial models seem to be rare.

Any suggestions for interface supporting `get` and `partialGet`?

**Comment by PhilippWendler** [comment]
Should there be an additional method `Object getVariableValue(String)`? I suspect that it is a common case, and if you do not know or care about the type of the variable, you cannot use `evaluate` and would need to use iteration.

Btw, partial models are not rare at all, CPAchecker only uses partial models. I agree that `Optional` does not make sense for methods returning `Object´.

**Comment by cheshire** [comment]
> Should there be an additional method `Object getVariableValue(String)`?

Nope, you can have two variables with the same name and a different type.

> Btw, partial models are not rare at all, CPAchecker only uses partial models

Or so it thinks :P
We have the following kinds of solvers:

 - Can be asked to give either partial or full models (Z3)
 - Only gives out partial models (Princess)
 - Only gives full models (Mathsat5 IIRC)

Ideally we would like to be able to choose between partial and full models, but I think due to solvers which only have partial models we can't.

I also think we should add an array of type-safe methods:

```java
@Nullable BigInteger evaluate(IntegerFormula f);
@Nullable Rational evaluate(RationalFormula f);
@Nullable Boolean evaluate(BooleanFormula f);
```

Also IIRC we use `BigInteger` for bitvector serialization, but it's not very well documented.

**Comment by cheshire** [comment]
Closing, re-open if there are any objections left.
#32 still stands open though.
