### ISSUE TITLE
Consider dropping wrapping methods from SmtInterpolEnvironment

### ISSUE THREAD

**Issue by cheshire** [sosy-lab/java-smt#48]
SmtInterpolEnvironment has a lot of wrapping methods whose sole job is to call the wrapped `Script` class, and change the thrown exception to an AssertionError (if an exception happens).
I think it would be beneficial to remove this wrapping as it hinders understanding (having to go through yet-another-hoop) and does not provide any value (both exceptions are RuntimeErrors and thus do not require declaring anyway).
I do not see any benefit for the calling code, as runtime errors are almost never supposed to be caught.
@PhilippWendler objections?

**Comment by PhilippWendler** [comment]
Sure, the code is a legacy from the time when `SMTLIBException` was checked.

**Comment by cheshire** [comment]
@kfriedberger Thanks! I've actually meant dropping the methods altogether by exposing the underlying Script object. Any objections on that?

**Comment by kfriedberger** [comment]
Exposing the underlying script might be one step too far, because we would also expose the central API of SMTInterpol to all components in the wrapper. In most methods we have additional checks (e.g. for stack-size) or some modification/matching on the output. I would like to keep the code as it is now.

**Comment by cheshire** [comment]
OK
