### ISSUE TITLE
Model for Z3 does not match solved formula with quantifiers

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#50]
I am solving a formula with quantifiers, UFs, and bitvectors and I need a model from Z3.
There are two problems with the returned model:

1) The model does not contain any values for the UFs that are in my input formula.
2) The model contains values for UFs that do not even appear in the input formula.

The first problem is a problem with JavaSMT, because the original Z3 model does mention my input UFs. You can see it in [this example](http://rise4fun.com/Z3/49kga), where `*signed_int@2` appears in the model, but the model returned from JavaSMT contains only
```
__ADDRESS_OF_test: 16374
*signed_int@2!11(16384): 2048
*signed_int@2!11(0): 4096
*signed_int@1!12(16384): 2048
*signed_int@1!12(16385): 0
*signed_int@1!12(0): 4096
```

The second problem is not per se a problem with JavaSMT, because the unwanted terms like `*signed_int@1!10` also appear in the original Z3 model, but I think it would be great if JavaSMT could filter out such unnecessary auxiliary value assignments.

**Comment by PhilippWendler** [comment]
Note that the auxiliary term `k!9` is already filtered out by JavaSMT, so I think it would be good to extend this for auxiliary terms like `*signed_int@1!12`, too.

**Comment by cheshire** [comment]
Hi,

0) Any chance of a reproducible example?
1) With a debugger, could you call Native.modelToString on a native object to be 100% sure that the problem is indeed in JavaSMT and that the returned model is different from what JavaSMT gives you?
JavaSMT definitely does support values for (even nested) UFs, I've tested that quite a bit.

JavaSMT does not do any filtering on the returned model, it should definitely just output whatever Z3 decides to return.

2) For the second problem, I would be very reluctant to try to be smarter than Z3, in order to keep JavaSMT simple. If it's indeed a bug in Z3, why not raise the issue on the Z3 bug tracker?

**Comment by PhilippWendler** [comment]
The example is linked in my post.
With this link you can also see the model that Z3 outputs directly and that it contains `*signed_int@2`.
The example also shows that `k!9` is present but it is not present in the JavaSMT model, so there is actually some filtering going on.
No user would ever be able to do something useful with values for `k!9` etc. because nobody except Z3 knows how these terms are defined, so I think there is no reason to not filter it, if it is possible (and if it is possible for `k!9`, then it should also be possible for `*signed_int@1!12`).

**Comment by cheshire** [comment]
Your example is an SMT-LIB input. It's still possible to make mistakes by translating API calls to an SMT-LIB problem, that's why I've suggested double-checking.
An a Java example would be much easier for me to debug.

All the code for generating the model is in the class Z3Model. It's very simple and it just iterates over the values Z3 provides, so I'm really not sure where the value could be lost...

**Comment by PhilippWendler** [comment]
Ok, sorry, you can reproduce it easily with CPAchecker:
```
int test[10] = {0};

void main() {
  if (test[0] != 0) {
ERROR:
    return;
  }
}
```

```
scripts/cpa.sh -predicateAnalysis-bitprecise -setprop cpa.predicate.useQuantifiersOnArrays=true -setprop solver.solver=z3
```

**Comment by kfriedberger** [comment]
I tried to fix this behaviour with commit ad13531a1695e95f673fc3657b922615e2d347e3 .
Now we should export evaluations for all symbols in the model, even for those that are aliased.
This has to be tested.

**Comment by PhilippWendler** [comment]
Now there are lots of AssertionErrors:
```
Exception in thread "main" java.lang.AssertionError
	at org.sosy_lab.solver.z3.Z3FormulaCreator.convertValue(Z3FormulaCreator.java:499)
	at org.sosy_lab.solver.z3.Z3Model.getConstAssignment(Z3Model.java:119)
	at org.sosy_lab.solver.z3.Z3Model.modelToList(Z3Model.java:91)
	at org.sosy_lab.solver.z3.Z3AbstractProver.getModelAssignments(Z3AbstractProver.java:53)
```

They are reproducible in CPAchecker by using the latest JavaSMT and the following command-line:
```
scripts/cpa.sh -predicateAnalysis-heaparray -setprop solver.solver=z3 -spec test/programs/simple/bitvectors/ALL.prp test/programs/simple/bitvectors/pointer_extension2_false-unreach-label.i
```

Printing the value that is attempted to be converted gives something like `(_ as-array k!0)`.

**Comment by kfriedberger** [comment]
This error `(_ as-array k!0)` is independent of the previous one.
The only common part here is the Z3-model, that might not be converted correctly in all cases.
The cause here is that the value of an array is an uninterpreted function (casted to array-type), 
where the only parameter of the function corresponds to the index of the array.
Instead of handling the cast, we throw an exception.
