### ISSUE TITLE
Cache BooleanFormulaManager.makeBoolean()?

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#51]
Should we cache the result of `BooleanFormulaManager.makeBoolean()`? Currently a fresh Formula object is always created.

Caching could be implemented easily in `AbstractBooleanFormulaManager` with two final fields for `true` and `false`.

As a related question, should we also add methods `makeTrue()` and `makeFalse()`?

**Comment by kfriedberger** [comment]
Caching: yes, good idea.
`makeTrue()`/`makeFalse()`: no, `makeBoolean()` is sufficient.

**Comment by kfriedberger** [comment]
If a solver produces `true`/`false` for itself (as part of a model or interpolant), the wrapped formula-object is also different. Perhaps caching has no big effect at all, and it might just be a cause of errors, if a user expects object-equality `==` for two formulas containing `true`.

**Comment by cheshire** [comment]
@PhilippWendler Actually I'm in favor of having private fields for caching and having `makeTrue`/`makeFalse`, sorry @kfriedberger . I was annoyed by not having them quite a few times.
It definitely will not cause extra errors.

In general, caching is a difficult subject.
Solvers _already_ do caching via hash-consing: so constructing multiple identical formulas will return identical native object (with no new allocation).
I was actually pondering on whether we should do hash-consing as well in order to avoid the overhead of extra `Formula` objects created, but currently I do not think it is a good idea.

**Comment by PhilippWendler** [comment]
If I try to do this and initialize the fields in the constructor of `AbstractBooleanFormulaManager`, I get segfaults with Z3 in `Z3_mk_true`. Do you have an idea how that could happen? As far as I could detect all initializations on the context are already done at that time.

**Comment by cheshire** [comment]
@PhilippWendler Can you show the actual code?
If you are just doing `BF cachedTrue = mkBoolean(true)`, you should be fine.

If that fails, doing things lazily would be definitely fine (cache on the first call).

**Comment by PhilippWendler** [comment]
For the record, my code is in c0934fc and the crash can be seen on [Travis](https://travis-ci.org/sosy-lab/java-smt/builds/141125374#L335).
