### ISSUE TITLE
Unable to run "ant publish-z3" under windows

### ISSUE THREAD

**Issue by danielratiu** [sosy-lab/java-smt#86]
I am trying to publish the z3 solver under windows by following the instructions from here:
https://github.com/sosy-lab/java-smt/blob/master/Developers.md

when running 'ant publish-z3 -Dz3.path=$Z3_DIR' I get an error:

D:\java-smt\build\build-publish-solvers.xml:17: Execute fai                    led: java.io.IOException: Cannot run program "lib\native\source\libz3j\wrap_memc                    py_in_z3.sh": CreateProcess error=193, %1 ist keine zul▒ssige Win32-Anwendung
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Jav                    a13CommandLauncher.java:58)
        at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:428)
        at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:442)
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:628)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:495)

**Comment by kfriedberger** [comment]
**Reason:**
The script `lib\native\source\libz3j\wrap_memcpy_in_z3.sh` is a bash-script and does not work on Windows.

**Possible Fix:**
Somone has to rewrite the script for Windows. 
Maybe it is even possible to run dash-scripts natively via Cygwin (I have not tried this).

**Background:**
Currently we do not really support solvers that are delivered as binaries (Z3, Mathsat) on Windows platforms, only Java-based solvers (SMTInterpol, Princess) are working.

**Comment by danielratiu** [comment]
> Currently we do not really support solvers that are delivered as binaries (Z3, Mathsat) on Windows platforms

is there a way to compile z3 from sources such that it would be usable (under Windows) from CPAchecker?

**Comment by PhilippWendler** [comment]
@kfriedberger There is no point at all in rewriting the script for Windows, because `ant publish-z3` is an internal command for JavaSMT developers, not for users of JavaSMT.

JavaSMT **does** support native solvers on Windows platforms (else it would be a bug). Please do not tell users the opposite. They binaries are just not supplied together with JavaSMT.

Having said that, I am sorry that I have caused a misunderstanding for Daniel. I linked to the developer's documentation as example how Z3 is compiled Z3 on Linux, because the [actual documentation for users](https://github.com/sosy-lab/java-smt#binaries-for-native-solvers-mathsat-and-z3) is not informative and only links to the developer information, too. I did not mean to imply to run the `publish-z3` command (which you could not do even if it worked on Windows, because it requires access to SoSy-Lab's Ivy repository).

But as can be seen from this case, the documentation can be confusing and should be improved. The user documentation should not just refer to the developer documentation, or make very clear which parts apply and which not. There is also a bug in the documentation because it tells users to grab the JAR file of Z3 but does not tell where to put it (it will not work in the `native` folder). Also we need to make it clear that the version of the solver needs to match exactly the one that JavaSMT needs, and how users can find this out.

@danielratiu Thanks for bringing this up. Could you please read https://github.com/sosy-lab/java-smt#binaries-for-native-solvers-mathsat-and-z3 and ask questions for everything that you don't understand, such that the documentation can be further improved.

**Comment by cheshire** [comment]
@danielratiu As you can see we don't really have much experience with running things on Windows :P  
Having said that, after the compilation of Z3 you should get a library file (it would be a `.dll` on windows, I believe).
If you just drop it in the folder `lib/native/x86_64-windows` (if you have a 64-bit Windows installation, or `lib/native/x86-windows` otherwise) in CPAchecker, I believe you should be good to go.

The situation with MathSAT is a bit more complicated, because we perform the compilation of the shared object ourselves, and I'm not sure whether it's possible to get it easily working on Windows.

@kfriedberger There is no reason at all for users to run `wrap_memcpy_in_z3.sh` as it simply replaces the `memcpy` function with the older version.
