### ISSUE TITLE
Transparent Delegation of Certain Queries to different Solver

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#9]
In CPAchecker, the feature exists that transparently for the user a different solver is used for interpolation queries than for other queries (with formulas serialized for communication between solvers). This is implemented in the class `SeparateInterpolatingProverEnvironment` and could be move to JavaSMT with a thin `FormulaManager` wrapper implementation.

The same could also be added for other kinds of queries.

**Comment by cheshire** [comment]
I'll have a go at this one. Ideally we would like to be able to transparently switch from solver to solver for various queries and tactics...

**Comment by cheshire** [comment]
> This is implemented in the class SeparateInterpolatingProverEnvironment and could be moved to JavaSMT 

JavaSMT currently does not have a class wrapping access to two different `FormulaManager` instances (what `Solver` does in `CPAchecker`).
`FormulaManagerFactory` can be used for that, but I am not sure whether using a field from a factory class would make sense.

We can make all `*ProverEnvironment` classes "context-safe" by adding an overhead pointer from `Formula` to the corresponding `FormulaManager`. Then each time a formula is used (e.g. `addAssertion`) we could check whether the `FormulaManager` matches and use serialization otherwise.
Would such an overhead be acceptable?

If we extend it to *all* methods taking formulas as input, we can fully transparently use formulas across different solvers and contexts.
That would save us from some bugs (e.g. the recent one with parsing the counterexample info), yet might be *too* transparent in a sense that we wouldn't even notice that formulas are coming from a different `FormulaManager`.
This approach would also simplify collaboration between different CPAs in CPAchecker (to use formulas from CPA B one would no longer need access to B's FormulaManager).

Feedback?

**Comment by PhilippWendler** [comment]
We should definitely *now* allow mixing formulas from different contexts IMO. That seems like a way to hide bugs for way too long. Explicit conversion between formulas is better than implicit.

Note that this is different than the situation of `SeparateInterpolatingProverEnvironment`. Here the conversion is part of the purpose of the class. It will still not allow the client to confuse and mix formulas from different contexts, and thus does not pose the same problems as doing the transparent conversion everywhere.

If we can add checks that prevent using formulas from a different context with a non-matching FormulaManager, we should do so, but I would not add the overhead of an extra field for that. For SMTInterpol, the field is not necessary because the SMTInterpol objects already have a field for that. For Z3 we already store the context anyway.

**Comment by cheshire** [comment]
Thus the question boils down to whether we should migrate `SeparateInterpolatingProverEnvironment`, which is already discussed in #6, so I'm closing this one.
